version: '2'

services:
  atmed_nginx:
    build: .
    image: sauravskumar/atmed_nginx
    container_name: atmed_nginx
    networks:
      - trains_default
      - sportsof_default
      - tutorialsof_default
    volumes:
      - /etc/nginx/ssl/atmed_co:/cert
    ports:
      - "80:80"
      - "443:443"

networks:
  trains_default:
    external: true
  sportsof_default:
    external: true
  tutorialsof_default:
    external: true