version: '2'

services:
  atmed_nginx:
    build: .
    image: sauravskumar/atmed_nginx
    container_name: atmed_nginx
    networks:
      - trains_default
      - coupons_default
      - atmedindex_default
      - tutorial_default
    volumes:
      - /etc/nginx/ssl/atmed_co:/cert
    ports:
      - "80:80"
      - "443:443"

networks:
  coupons_default:
    external: true
  trains_default:
    external: true
  atmedindex_default:
    external: true
  tutorial_default:
    external: true