version: '2'

services:
  atmed_nginx:
    image: sauravskumar/nginx
    container_name: atmed_nginx
    networks:
      - trains_default
      - coupons_default
    volumes:
      - /etc/nginx/ssl/atmed_co:/cert
    ports:
      - "80:80"

networks:
  coupons_default:
    external: true
  trains_default:
    external: true