version: '2'

services:
  atmed_nginx:
    image: sauravskumar/nginx
    container_name: atmed_nginx
    networks:
      - coupons_default
    ports:
      - "80:80"

networks:
  coupons_default:
    external: true